project: 
  type: website
  
website: 
  page-navigation: true
  title: "GLOBGM_CMIP6" 
  site-url: https://vanjaarsveldbarry.github.io/globgm_cmip6/
  repo-url: https://github.com/vanjaarsveldbarry/globgm_cmip6
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    
  sidebar:
    logo: "images/LogoGEOWAT.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://globalhydrology.nl/research/models/pcr-globwb-2-0/
      - icon: github
        href: https://github.com/vanjaarsveldbarry/globgm_cmip6

    style: "docked"
    search: true
    collapse: false
    contents:
      - href: index.qmd
        text: Introduction

      - href: data_catalogue/data_catalogue.qmd
        text: "Data Catalogue"

      - href: data_access/data_access.qmd
        text: "Data Access"


format:
  html:
    theme: 
      - default
      - custom-styles.scss
    code-copy: true
    code-overflow: wrap
    toc: true
