---
title: "Data Catalogue"
toc: false
---


## Historical

| Temporal Resolution | Name                                                | Size (Gb)| Files | Download Link                                                                                             |
|---                  |---                                                  |---       |---    |---                                                                                                        |
| Average             |                                                     |          |       |                                                                                                           |
|                     | hds_reference_gswp3-w5e5_average_1960_2019.nc       | 5.3      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_reference_gswp3-w5e5_average_1960_2019.nc       | 5.3      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
| Annual              |                                                     |          |       |                                                                                                           |
|                     | hds_reference_gswp3-w5e5_annual_1960_2019.zarr.zip  | 48       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_reference_gswp3-w5e5_annual_1960_2019.zarr.zip  | 48       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
| Monthly             |                                                     |          |       |                                                                                                           |
|                     | hds_reference_gswp3-w5e5_monthly_1960_2019.zarr.zip | 574      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_reference_gswp3-w5e5_monthly_1960_2019.zarr.zip | 659      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |

## CMIP6 Ensemble
This is the mean over the 5 GCMs we ran.

| Temporal Resolution | Name                                               | Size (Gb)| Files | Download Link                                                                                             |
|---                  |---                                                 |---       |---    |---                                                                                                        |
| Average             |                                                    |          |       |                                                                                                           |
|                     | hds_average_1960_2014_historical_ensemble.nc       | 5        |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | hds_average_2015_2100_ssp126_ensemble.nc           | 5        |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | hds_average_2015_2100_ssp370_ensemble.nc           | 5        |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | hds_average_2015_2100_ssp585_ensemble.nc           | 5        |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_average_1960_2014_historical_ensemble.nc       | 5        |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_average_2015_2100_ssp126_ensemble.nc           | 5        |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_average_2015_2100_ssp370_ensemble.nc           | 5        |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_average_2015_2100_ssp585_ensemble.nc           | 5        |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
| Annual              |                                                    |          |       |                                                                                                           |
|                     | hds_annual_1960_2014_historical_ensemble.zarr.zip  | 44       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | hds_annual_2015_2100_ssp126_ensemble.zarr.zip      | 69       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | hds_annual_2015_2100_ssp370_ensemble.zarr.zip      | 69       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | hds_annual_2015_2100_ssp585_ensemble.zarr.zip      | 69       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_annual_1960_2014_historical_ensemble.zarr.zip  | 50       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_annual_2015_2100_ssp126_ensemble.zarr.zip      | 79       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_annual_2015_2100_ssp370_ensemble.zarr.zip      | 79       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_annual_2015_2100_ssp585_ensemble.zarr.zip      | 79       |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
| Monthly             |                                                    |          |       |                                                                                                           |
|                     | hds_monthly_1960_2014_historical_ensemble.zarr.zip | 526      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | hds_monthly_2015_2100_ssp126_ensemble.zarr.zip     | 826      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | hds_monthly_2015_2100_ssp370_ensemble.zarr.zip     | 826      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | hds_monthly_2015_2100_ssp585_ensemble.zarr.zip     | 826      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_monthly_1960_2014_historical_ensemble.zarr.zip | 603      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_monthly_2015_2100_ssp126_ensemble.zarr.zip     | 945      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_monthly_2015_2100_ssp370_ensemble.zarr.zip     | 945      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
|                     | wtd_monthly_2015_2100_ssp585_ensemble.zarr.zip     | 945      |       |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |

## CMIP6 GCM
This ese are the GCM's, we only provide annual and monthly

| Temporal Resolution | Name                                                   | Size (Gb)| Files | Download Link                                                                                             |
|---                  |---                                                     |---       |---    |---                                                                                                        |
| Average             |                                                        |          |       |                                                                                                           |
|                     | hds_ average_1960_2014_historical_ipsl-cm6a-lr.nc      | 44       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_1960_2014_historical_mpi-esm1-2-hr.nc     | 44       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_1960_2014_historical_mri-esm2-0.nc        | 44       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_1960_2014_historical_ukesm1-0-ll.nc       | 44       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp126_gfdl-esm4.nc             | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp126_ipsl-cm6a-lr.nc          | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp126_mpi-esm1-2-hr.nc         | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp126_mri-esm2-0.nc            | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp126_ukesm1-0-ll.nc           | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp370_gfdl-esm4.nc             | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp370_ipsl-cm6a-lr.nc          | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp370_mpi-esm1-2-hr.nc         | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp370_mri-esm2-0.nc            | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp370_ukesm1-0-ll.nc           | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp585_gfdl-esm4.nc             | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp585_ipsl-cm6a-lr.nc          | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp585_mpi-esm1-2-hr.nc         | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp585_mri-esm2-0.nc            | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_ average_2015_2100_ssp585_ukesm1-0-ll.nc           | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_1960_2014_historical_gfdl-esm4.nc         | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_1960_2014_historical_ipsl-cm6a-lr.nc      | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_1960_2014_historical_mpi-esm1-2-hr.nc     | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_1960_2014_historical_mri-esm2-0.nc        | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_1960_2014_historical_ukesm1-0-ll.nc       | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp126_gfdl-esm4.nc             | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp126_ipsl-cm6a-lr.nc          | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp126_mpi-esm1-2-hr.nc         | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp126_mri-esm2-0.nc            | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp126_ukesm1-0-ll.nc           | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp370_gfdl-esm4.nc             | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp370_ipsl-cm6a-lr.nc          | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp370_mpi-esm1-2-hr.nc         | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp370_mri-esm2-0.nc            | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp370_ukesm1-0-ll.nc           | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp585_gfdl-esm4.nc             | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp585_ipsl-cm6a-lr.nc          | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp585_mpi-esm1-2-hr.nc         | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp585_mri-esm2-0.nc            | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_ average_2015_2100_ssp585_ukesm1-0-ll.nc           | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
| Annual              |                                                        |          |       |                                                                                                           |
|                     | hds_annual_1960_2014_historical_ipsl-cm6a-lr.zarr.zip  | 44       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_1960_2014_historical_mpi-esm1-2-hr.zarr.zip | 44       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_1960_2014_historical_mri-esm2-0.zarr.zip    | 44       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_1960_2014_historical_ukesm1-0-ll.zarr.zip   | 44       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp126_gfdl-esm4.zarr.zip         | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp126_ipsl-cm6a-lr.zarr.zip      | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp126_mpi-esm1-2-hr.zarr.zip     | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp126_mri-esm2-0.zarr.zip        | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp126_ukesm1-0-ll.zarr.zip       | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp370_gfdl-esm4.zarr.zip         | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp370_ipsl-cm6a-lr.zarr.zip      | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp370_mpi-esm1-2-hr.zarr.zip     | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp370_mri-esm2-0.zarr.zip        | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp370_ukesm1-0-ll.zarr.zip       | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp585_gfdl-esm4.zarr.zip         | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp585_ipsl-cm6a-lr.zarr.zip      | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp585_mpi-esm1-2-hr.zarr.zip     | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp585_mri-esm2-0.zarr.zip        | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | hds_annual_2015_2100_ssp585_ukesm1-0-ll.zarr.zip       | 69       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_1960_2014_historical_gfdl-esm4.zarr.zip     | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_1960_2014_historical_ipsl-cm6a-lr.zarr.zip  | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_1960_2014_historical_mpi-esm1-2-hr.zarr.zip | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_1960_2014_historical_mri-esm2-0.zarr.zip    | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_1960_2014_historical_ukesm1-0-ll.zarr.zip   | 50       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp126_gfdl-esm4.zarr.zip         | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp126_ipsl-cm6a-lr.zarr.zip      | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp126_mpi-esm1-2-hr.zarr.zip     | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp126_mri-esm2-0.zarr.zip        | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp126_ukesm1-0-ll.zarr.zip       | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp370_gfdl-esm4.zarr.zip         | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp370_ipsl-cm6a-lr.zarr.zip      | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp370_mpi-esm1-2-hr.zarr.zip     | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp370_mri-esm2-0.zarr.zip        | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp370_ukesm1-0-ll.zarr.zip       | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp585_gfdl-esm4.zarr.zip         | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp585_ipsl-cm6a-lr.zarr.zip      | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp585_mpi-esm1-2-hr.zarr.zip     | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp585_mri-esm2-0.zarr.zip        | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     
|                     | wtd_annual_2015_2100_ssp585_ukesm1-0-ll.zarr.zip       | 78       |       | [Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |     

## Quality Warning
| Name                    | Size (Gb)| Files | Download Link                                                                                             |
|---                      |---       |---    |---                                                                                                        |
| spin_up_1960.nc         |  0.7     |  1    |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
| spin_up_1990.nc         |  0.7     |  1    |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
| spin_up_2030.nc         |  0.7     |  1    |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
| spin_up_2070.nc         |  0.7     |  1    |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
| static_quality_flags.nc |  2.7     |  1    |[Download](https://geo.public.data.uu.nl/vault-globgm/research-globgm%5B1669042611%5D/original/README.txt) |
