---
title: "Cite this Work"
toc: false
---

When using GLOBGM CMIP6 data in your work, please cite the relevant dataset(s) in addition to the manuscript. Each dataset receives a unique DOI through the Yoda data repository and should be cited according to DataCite standards. Please cite the specific dataset(s) you use in your analysis. If you use multiple scenarios or time periods, cite all relevant datasets.


### Publication Citation

::: {#refs}
van Jaarsveld, B., Wanders, N., Otoo, N.G., Sutanudjaja, E.H., Verkaik, J., Zamrsky, D., and Bierkens, M.F.P. (2026). Global hyper-resolution modeling of historical and future groundwater dynamics, *EGUsphere [preprint]*, <https://doi.org/10.5194/egusphere-2026-804>.
:::


```{.bibtex .code-overflow-wrap}
@Article{vanJaarsveld2025global,
AUTHOR={van Jaarsveld, B. and Wanders, N. and Otoo, N.G. and Sutanudjaja, E.H. and Verkaik, J. and Zamrsky, D. and Bierkens, M.F.P.},
TITLE={Global hyper-resolution modeling of historical and future groundwater dynamics},
JOURNAL={Earth System Dynamics [preprint]},
YEAR={2025},
DOI={10.5194/egusphere-2026-804},
URL={https://egusphere.copernicus.org/preprints/2026/egusphere-2026-804/}
}
```

### Dataset Citation

1. **Historical Reference:**
   van Jaarsveld, B., et al. (2025). *GLOBGM_CMIP6: A Global Hyper-Resolution Groundwater Dataset for Assessing Historical and Future Groundwater Dynamics Under Climate and Socioeconomic Change - [globgm_historical_reference_gswp3-w5e5]*. Utrecht University. <https://doi.org/10.24416/UU01-AKSHOX>

2. **Climate Projections: Monthly**
   van Jaarsveld, B., et al. (2025). *GLOBGM_CMIP6: A Global Hyper-Resolution Groundwater Dataset for Assessing Historical and Future Groundwater Dynamics Under Climate and Socioeconomic Change - [ssp_rcp_monthly]*. Utrecht University. <https://doi.org/10.24416/UU01-1BXLPD>

3. **Climate Projections: Annual**
   van Jaarsveld, B., et al. (2025). *GLOBGM_CMIP6: A Global Hyper-Resolution Groundwater Dataset for Assessing Historical and Future Groundwater Dynamics Under Climate and Socioeconomic Change - [ssp_rcp_annual]*. Utrecht University. <https://doi.org/10.24416/UU01-V6B9YS>

4. **Climate Projections: Average**
   van Jaarsveld, B., et al. (2025). *GLOBGM_CMIP6: A Global Hyper-Resolution Groundwater Dataset for Assessing Historical and Future Groundwater Dynamics Under Climate and Socioeconomic Change - [ssp_rcp_average]*. Utrecht University. <https://doi.org/10.24416/UU01-SLRFI7>

5. **Quality Assurance**
   van Jaarsveld, B., et al. (2025). *GLOBGM_CMIP6: A Global Hyper-Resolution Groundwater Dataset for Assessing Historical and Future Groundwater Dynamics Under Climate and Socioeconomic Change - [quality_assurance]*. Utrecht University. <https://doi.org/10.24416/UU01-16EJ3Y>
