---
title: ""
---

<div style="text-align: center;">
  <h3>HPC Access</h3>
</div>

This guide provides instructions for accessing the GLOBGM dataset on High-Performance Computing (HPC) systems. The recommended method depends on your specific system and preferences.


<div style="text-align: center;">
  <h3>Download Remote Data</h3>
</div>

The primary method for downloading the complete dataset is directly from the YODA (Your Data) repository. Several command-line tools can be used for this purpose, including wget for recursive downloading, or iRODS clients like iCommands and iBridges for more advanced data management.

A general wget command to recursively download a directory is as follows:


```bash
wget -r -P PATH_ON_LOCAL_FILE_SYSTEM URL_TO_FOLDER_ON_YODA 
```

<div style="text-align: center;">
  <h3>Snellius Users</h3>
</div>


We are actively working to make the GLOBGM dataset available as a managed dataset on the Snellius supercomputer. This will enable direct and optimized access for all Snellius users. Please watch this space for future updates on availability.

In the interim, users on Snellius can request direct access to the data. Please contact the project administrator to arrange a data transfer via the scratch file system.