name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Miniconda and Create Environment
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          eval "$($HOME/miniconda/bin/conda shell.bash hook)"
          conda create -y -n quarto-env -c conda-forge python=3.10 jupyter nbformat ipykernel itables
          conda activate quarto-env
          python -m ipykernel install --user --name quarto-env

      - name: Add Conda environment to PATH
        run: |
          echo "$HOME/miniconda/envs/quarto-env/bin" >> $GITHUB_PATH

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PYTHON: $HOME/miniconda/envs/quarto-env/bin/python
