# .github/workflows/publish.yml

name: Quarto Publish

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        # Give this step an ID to reference its outputs later
        id: setup-conda 
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: quarto-env
          use-mamba: true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Point Quarto to the Python from our Conda environment
          QUARTO_PYTHON: ${{ steps.setup-conda.outputs.conda-prefix }}/bin/python
