name: Quarto Publish

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        id: setup-conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: quarto-env
          use-mamba: true

      - name: Add Conda environment to PATH
        run: |
          echo "${{ steps.setup-conda.outputs.conda-prefix }}/bin" >> $GITHUB_PATH

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PYTHON: ${{ steps.setup-conda.outputs.conda-prefix }}/bin/python
